package com.ora.wellbeing.data.model

import com.google.firebase.Timestamp
import com.google.firebase.firestore.IgnoreExtraProperties
import com.google.firebase.firestore.PropertyName

/**
 * User Recommendation Models
 * Stores personalized lesson recommendations generated by Cloud Functions
 * Stored in users/{uid}/recommendations/{id}
 *
 * IMPORTANT: Firestore uses snake_case field names
 */

@IgnoreExtraProperties
class RecommendationContext {
    var intentions: List<String> = emptyList()

    @get:PropertyName("experience_levels")
    @set:PropertyName("experience_levels")
    var experienceLevels: Map<String, String> = emptyMap()

    @get:PropertyName("time_commitment")
    @set:PropertyName("time_commitment")
    var timeCommitment: String = ""

    @get:PropertyName("completed_lesson_ids")
    @set:PropertyName("completed_lesson_ids")
    var completedLessonIds: List<String> = emptyList()

    constructor()

    constructor(
        intentions: List<String>,
        experienceLevels: Map<String, String>,
        timeCommitment: String,
        completedLessonIds: List<String>
    ) {
        this.intentions = intentions
        this.experienceLevels = experienceLevels
        this.timeCommitment = timeCommitment
        this.completedLessonIds = completedLessonIds
    }
}

@IgnoreExtraProperties
class RecommendationMetadata {
    @get:PropertyName("total_lessons_scored")
    @set:PropertyName("total_lessons_scored")
    var totalLessonsScored: Int = 0

    @get:PropertyName("avg_score")
    @set:PropertyName("avg_score")
    var avgScore: Double = 0.0

    var trigger: String = ""

    constructor()

    constructor(
        totalLessonsScored: Int,
        avgScore: Double,
        trigger: String
    ) {
        this.totalLessonsScored = totalLessonsScored
        this.avgScore = avgScore
        this.trigger = trigger
    }
}

/**
 * User recommendation document
 * Stored in: users/{uid}/recommendations/{id}
 *
 * Document IDs:
 * - "latest" - Most recent recommendation (always updated)
 * - "onboarding_complete" - Generated after onboarding
 * - "2025-12-08" - Weekly CRON (date format)
 * - "manual" - Manually regenerated
 */
@IgnoreExtraProperties
class UserRecommendation {
    var uid: String = ""

    @get:PropertyName("lesson_ids")
    @set:PropertyName("lesson_ids")
    var lessonIds: List<String> = emptyList()

    var scores: Map<String, Double> = emptyMap()

    @get:PropertyName("generated_at")
    @set:PropertyName("generated_at")
    var generatedAt: Timestamp? = null

    @get:PropertyName("algorithm_version")
    @set:PropertyName("algorithm_version")
    var algorithmVersion: String = "1.0.0"

    @get:PropertyName("based_on")
    @set:PropertyName("based_on")
    var basedOn: RecommendationContext? = null

    var metadata: RecommendationMetadata? = null

    constructor()

    constructor(
        uid: String,
        lessonIds: List<String>,
        scores: Map<String, Double>,
        generatedAt: Timestamp?,
        algorithmVersion: String,
        basedOn: RecommendationContext?,
        metadata: RecommendationMetadata?
    ) {
        this.uid = uid
        this.lessonIds = lessonIds
        this.scores = scores
        this.generatedAt = generatedAt
        this.algorithmVersion = algorithmVersion
        this.basedOn = basedOn
        this.metadata = metadata
    }

    /**
     * Check if recommendations are stale (older than 7 days)
     */
    fun isStale(): Boolean {
        val generated = generatedAt?.toDate()?.time ?: return true
        val sevenDaysMs = 7 * 24 * 60 * 60 * 1000L
        return System.currentTimeMillis() - generated > sevenDaysMs
    }

    /**
     * Get the trigger type as enum
     */
    fun getTriggerType(): RecommendationTrigger {
        return when (metadata?.trigger) {
            "onboarding_complete" -> RecommendationTrigger.ONBOARDING_COMPLETE
            "weekly_cron" -> RecommendationTrigger.WEEKLY_CRON
            "manual" -> RecommendationTrigger.MANUAL
            else -> RecommendationTrigger.UNKNOWN
        }
    }
}

/**
 * Enum for recommendation trigger types
 */
enum class RecommendationTrigger {
    ONBOARDING_COMPLETE,
    WEEKLY_CRON,
    MANUAL,
    UNKNOWN
}
