package com.ora.wellbeing.domain.repository

import com.ora.wellbeing.data.model.ContentItem
import com.ora.wellbeing.data.model.UserRecommendation
import kotlinx.coroutines.flow.Flow

/**
 * Repository interface for personalized recommendations
 * Collection: users/{uid}/recommendations/{id}
 *
 * Recommendations are generated by Cloud Functions based on:
 * - User onboarding responses (intentions, experience levels, time commitment)
 * - Completed lessons (to exclude already watched content)
 * - Active programs (to exclude lessons from enrolled programs)
 *
 * Triggers:
 * - onboarding_complete: Immediately after user completes onboarding
 * - weekly_cron: Every Monday at 3:00 AM UTC
 * - manual: When admin regenerates recommendations
 */
interface RecommendationRepository {

    /**
     * Observes the latest recommendations for a user
     * Returns the "latest" recommendation document which is always up-to-date
     *
     * @param uid User ID
     * @return Reactive Flow of the recommendation document (null if not generated yet)
     */
    fun getLatestRecommendation(uid: String): Flow<UserRecommendation?>

    /**
     * Observes personalized content recommendations for a user
     * Fetches the lesson details for each recommended lesson ID
     *
     * @param uid User ID
     * @param limit Maximum number of lessons to return (default 5)
     * @return Reactive Flow of recommended ContentItems
     */
    fun getRecommendedContent(uid: String, limit: Int = 5): Flow<List<ContentItem>>

    /**
     * Checks if user has recommendations generated
     *
     * @param uid User ID
     * @return true if recommendations exist, false otherwise
     */
    suspend fun hasRecommendations(uid: String): Boolean

    /**
     * Gets the recommendation history for a user
     * Returns all recommendation documents ordered by generated_at DESC
     *
     * @param uid User ID
     * @param limit Maximum number of historical recommendations to return
     * @return List of UserRecommendation documents
     */
    suspend fun getRecommendationHistory(uid: String, limit: Int = 10): List<UserRecommendation>

    /**
     * Force refresh recommendations from Firestore
     * Useful after detecting that recommendations might be stale
     *
     * @param uid User ID
     */
    suspend fun refreshRecommendations(uid: String)
}
